server:
  port: 8080
  
spring:
  application:
    name: crime-registration-detection
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  users: 
    datasource:
      url: jdbc:mysql://localhost:3306/users
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  crimes:
    datasource2:
      url: jdbc:mysql://localhost:3306/crime_registration_detection
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver